// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANLcYTIzY2PCqf-vDNPOkvXyCXwe7Ius',
    appId: '1:1061507424704:web:104a19f53438e415466825',
    messagingSenderId: '1061507424704',
    projectId: 'docapp-51369',
    authDomain: 'docapp-51369.firebaseapp.com',
    storageBucket: 'docapp-51369.appspot.com',
    measurementId: 'G-8GFSKHJVV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSkvmLEtHsOGIKk3_gBdK8CeAhFEMI_dw',
    appId: '1:1061507424704:android:3187f097684f3af1466825',
    messagingSenderId: '1061507424704',
    projectId: 'docapp-51369',
    storageBucket: 'docapp-51369.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcsebQ-Jw1K38zBJ1YGPN-WK4g_t3ysnw',
    appId: '1:1061507424704:ios:4323537daf3481fa466825',
    messagingSenderId: '1061507424704',
    projectId: 'docapp-51369',
    storageBucket: 'docapp-51369.appspot.com',
    iosBundleId: 'com.example.flutterAdvancedTopics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcsebQ-Jw1K38zBJ1YGPN-WK4g_t3ysnw',
    appId: '1:1061507424704:ios:3b247c45baec99e2466825',
    messagingSenderId: '1061507424704',
    projectId: 'docapp-51369',
    storageBucket: 'docapp-51369.appspot.com',
    iosBundleId: 'com.example.flutterAdvancedTopics.RunnerTests',
  );
}
